name: Android Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: "build apk"
        uses: docker://thyrlian/android-sdk
        with:
          args: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: app/build/outputs/apk/debug/
